### PR TITLE
Juan Chavez's Blog Post

### PR DESCRIPTION
**Pull request by chavez-ju**
Juans blogpost

### CODE REVIEW

**Comment by chavez-ju** [comment]
I will be developing a class that makes a general-purpose queue manager that can be used across all interactive Empirical websites. Its' planned to have a button that you can click to add a specified number of runs to the queue. The queue manager should consult the current parameter values in a config object (see tools/config) to select the parameter values to use for those runs. Also, it should have a display that shows the runs that are currently queued and whether they are currently “waiting”, “running”, or “done”. Lastly, it should control the process of running the main code once for every item in the queue, with the correct parameters

**Comment by uma-sethuraman** [comment]
I think this outline looks great and does a nice job of summarizing all the key components of your project! 

Here is my feedback on your outline: 

- In or after the QueueManager Implementation section, I think it would be helpful to discuss examples of how the QueueManager can be used in future code for those who want to use it in future projects.

- In the final blog post, I think it would also be nice to have some graphic showing the general functionality of the QueueManager so that it's easier to visualize for future users. This could be in the QueueManager Implementation section as well.

- Perhaps in the conclusion section or in a separate section, you could have a graph or visualization showing the changes in runtime performance from the previous implementation to your implementation. 

- In the conclusion section, it would be good to also specify who your mentor and the other developers you worked with are, since you do have a bullet point in that section which talks about your experience working with them.

Overall, I think the outline looks very good, and your project looks so interesting and impressive! I'm excited to see the final blog post!

**Comment by caovicto** [comment]
### Intro ###
- I believe you can you use this for an embedded video
`<iframe width="560" height="315" src="https://www.youtube.com/watch?v=t9Lo2fgxWHw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
- An image of the truth table for the dilemma might also be a nice addition if you can find one on google.

### Implementation ###
- I'm not sure how long your code is, but a simple walkthrough of the tools you created and the actual implementation could be a nice addition.
- Having a challenges subtitle on the config library, and others would allow the reader to stay present in the current topic you're talking about as opposed to breaking it up into all your implementation choices, then all the challenges.

### Overall ###
- Adding subtitles, code snippets, easy pictures to find off google, and highlighting/bolding if necessary would be good visual additions to your blog.
- Nice Outline, it seems clear and covers your topic well!

**Comment by qinyi2000** [comment]
Hi Juan,

I like your blog post. Here are some comments I have:

**Pros**:
- Nice background intro on the Prisoner's Dilemma Problem.
- I like how you listed the technologies/settings you've used.
- The takeaways are really nice as they inspire newcomers.

**Things to improve:**
- The line <iframe width="560" height="315" src="https://www.youtube.com/watch?v=t9Lo2fgxWHw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> is not rendered correctly in the Markdown
- The line Mentor: Emily Dolson [Emily Dolson]({{ site.baseurl }}/assets/headshots/square-EmilyDolson.png){:style="width: 130px; align: center;"} is also not rendered in Markdown.
- The section header "Simple PD World application" can be renamed to something like "Context Introduction" for clarity. When I was reading I confused your implementation with the PD app of Empirical. It would also be good to mention the name of your project "QueueManager" in the "Simple PD World application" to make it absolutely clear which project you are referring to.
- You can add a little more details to the Challenges section.

**Pull request merged**
